version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/var/www/html
    environment:
      - APP_URL=http://localhost:8000
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    networks:
      - app-network

  frontend:
    build: ./FrondEnd
    ports:
      - "5173:5173"
    volumes:
      - ./FrondEnd:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/graphql
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge