# fly.toml app configuration file generated for jlo-fullstack on 2024-11-29T17:25:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jlo-fullstack"
primary_region = "cdg"

[build]
  dockerfile = "Backend/Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  DB_CONNECTION = "sqlite"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
